#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""jjstack 生成器：从模板渲染 SKILL.md。

约定（对齐 gstack 的做法）：**SKILL.md 是生成物，不要直接改 SKILL.md。**
改 `jj-*/SKILL.tmpl` 或 `jjstack/lib/preamble.md`，然后运行本脚本。
`validate.py` 的 freshness 检查会发现手改 SKILL.md 导致的漂移。

用法：
  python3 scripts/gen-skills.py            # 生成全部
  python3 scripts/gen-skills.py --check    # 只检查是否最新（不写盘），CI 用
"""
import argparse
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PREAMBLE = os.path.join(ROOT, 'lib', 'preamble.md')


def layout():
    """两种布局都支持。

    仓库态：ROOT 是路由技能本身，子技能是它的子目录（对齐 gstack 的仓库形状）
    安装态：ROOT 是 ~/.agents/skills/jjstack，子技能是它的兄弟目录
    """
    inside = sorted(d for d in os.listdir(ROOT)
                    if d.startswith('jj-') and os.path.isdir(os.path.join(ROOT, d)))
    if inside:
        # 仓库态：ROOT 自身就是路由器技能，子技能是它的子目录
        return ROOT, [ROOT] + [os.path.join(ROOT, d) for d in inside]
    parent = os.path.dirname(ROOT)
    sibs = sorted(d for d in os.listdir(parent)
                  if d.startswith('jj-') and os.path.isdir(os.path.join(parent, d)))
    return parent, [os.path.join(parent, d) for d in sibs] + [ROOT]


SKILLS_DIR, SKILL_DIRS = layout()
GENERATED_MARK = '<!-- GENERATED from {tmpl} — do not edit this file. Regenerate: python3 scripts/gen-skills.py -->'


def read(path):
    with open(path, encoding='utf-8') as f:
        return f.read()


def render(tmpl_path):
    """frontmatter + 生成标记 + 启动块 + 正文。"""
    raw = read(tmpl_path)
    m = re.match(r'^---\n(.*?\n)---\n(.*)$', raw, re.S)
    if not m:
        raise SystemExit(f'缺少 frontmatter: {tmpl_path}')
    front, body = m.group(1), m.group(2)
    preamble = read(PREAMBLE).strip()
    body = re.sub(r'\{\{PREAMBLE\}\}', preamble, body, count=1)
    name = os.path.relpath(tmpl_path, SKILLS_DIR)
    return f'---\n{front}---\n\n{GENERATED_MARK.format(tmpl=name)}\n\n{body.strip()}\n'


def targets():
    out = []
    for d in SKILL_DIRS:
        tmpl = os.path.join(d, 'SKILL.tmpl')
        if os.path.exists(tmpl):
            out.append((tmpl, os.path.join(d, 'SKILL.md')))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true', help='不写盘，只报告漂移')
    args = ap.parse_args()

    drift, written = [], []
    for tmpl, out in targets():
        want = render(tmpl)
        have = read(out) if os.path.exists(out) else None
        if have == want:
            continue
        if args.check:
            drift.append(os.path.relpath(out, SKILLS_DIR))
        else:
            with open(out, 'w', encoding='utf-8') as f:
                f.write(want)
            written.append(os.path.relpath(out, SKILLS_DIR))

    if args.check:
        if drift:
            print('SKILL DOCS DRIFT:')
            for d in drift:
                print('  -', d)
            print('修复: python3 scripts/gen-skills.py')
            return 1
        print('skill docs fresh: 全部最新')
        return 0

    for w in written:
        print('wrote', w)
    print(f'完成：{len(written)} 个文件更新，{len(targets()) - len(written)} 个已最新')
    return 0


if __name__ == '__main__':
    sys.exit(main())
